with open('accessions_subset.txt', 'rt') as fp:
    ACCESSIONS = fp.readlines()
    ACCESSIONS = [ line.strip() for line in ACCESSIONS ]
    
print(f'ACCESSIONS is a Python list of length {len(ACCESSIONS)}')
print(ACCESSIONS)

rule all:
    input:
        expand("results/filtered_fastqs/{acc}.fastq.gz", acc=ACCESSIONS),
        expand("results/filtered_fastqs/{acc}.fastq.gz", acc=ACCESSIONS),
        
rule fastp:
    input:
        r1 = "frem_reads/{query}_{loop}_R1_001.fastq.gz",
        r2 = "frem_reads/{query}_{loop}_R2_001.fastq.gz"
    output:
        r1 = "results/filtered_fastqs/{query}_{loop}_R1_001.fastq.gz",
        r2 = "results/filtered_fastqs/{query}_{loop}_R2_001.fastq.gz",
        summ = "results/summary_stats/{query}_{loop}.fastp.out"
    conda:
        "../envs/fastq2bam.yml"
    log:
        "logs/fastp/{query}/{loop}.txt"
    benchmark:
        "benchmarks/fastp/{query}/{loop}.txt"
    shell:
        "fastp --in1 {input.r1} --in2 {input.r2} "
        "--out1 {output.r1} --out2 {output.r2} "
        "--thread {threads} "
        "--detect_adapter_for_pe "
        "-j /dev/null -h /dev/null "
        "2> {output.summ} > {log}"

